// Mocks generated by Mockito 5.4.2 from annotations
// in rivalx/test/blocs/challenge/challenge_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rivalx/services/firestore_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> getDocument(
    String? collection,
    String? documentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [
            collection,
            documentId,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getCollection(String? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollection,
          [collection],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> setDocument(
    String? collection,
    String? documentId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDocument,
          [
            collection,
            documentId,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument(
    String? collection,
    String? documentId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [
            collection,
            documentId,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(
    String? collection,
    String? documentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [
            collection,
            documentId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, dynamic>?> documentStream(
    String? collection,
    String? documentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentStream,
          [
            collection,
            documentId,
          ],
        ),
        returnValue: _i3.Stream<Map<String, dynamic>?>.empty(),
      ) as _i3.Stream<Map<String, dynamic>?>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> collectionStream(String? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionStream,
          [collection],
        ),
        returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
      ) as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> addDocument(
    String? collection,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDocument,
          [
            collection,
            data,
          ],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}